#!/usr/bin/env bash
source /etc/profile
set -e
oldrev=$1
newrev=$2

run() {
  [ -x $1 ] && $1 $oldrev $newrev
}

umask 002

# Sync any git submodules and update them
git submodule init && git submodule sync && git submodule update

# Run the deploy script
set +e
run deploy/deploy
if [ "$?" -ne 0 ]; then
  echo -e "\e[0;31m===> Deploy Fail\033[0m"; exit 1;
else
  run deploy/notify
  # Clean all
  echo -e "\e[0;32m===> Cleanup\033[0m"
  git clean -d -x -f

  echo -e "\e[0;32m===> Tagging the build\033[0m"
  # All good tag the build
  git tag build-$(date -u +%Y%m%d-%H%M%S%z)
fi
