#!/usr/bin/env bash
set -e
oldrev=$1
newrev=$2

run() {
  [ -x $1 ] && $1 $oldrev $newrev
}

umask 002

# Sync any git submodules and update them
git submodule init && git submodule sync && git submodule update

# Run the deploy script
set +e
run deploy/deploy
if [ "$?" -ne 0 ]; then
  echo "===> Deploy Fail"; exit 1;
else
  run deploy/notify
  # Clean all
  echo "===> Cleanup"
  git clean -d -x -f

  echo "===> Tagging the build"
  # All good tag the build
  git tag build-$(date +%s)
fi
set -e
