#!/usr/bin/env bash
set -e

echo -e "\e[0;32m===> Stopping tomcat6 service\033[0m"
sudo service tomcat6 stop

echo -e "\e[0;32m===> Building project\033[0m"
gradle compressAll
gradle -PLOGBACK_APPENDER=FILE -PLOGBACK_LOG_FILE_LOCATION=/srv/logs clean war -x test
sed -i 's/git\.sha\=.*/git\.sha\='$2'/g' /srv/config/*.properties

echo -e "\e[0;32m===> Remove previous war\033[0m"
sudo rm -rf /var/lib/tomcat6/webapps/ROOT*

echo -e "\e[0;32m===> Moving new war to the webapps dir\033[0m"
sudo cp build/libs/changeme-1.0-SNAPSHOT.war /var/lib/tomcat6/webapps/ROOT.war

echo -e "\e[0;32m===> Starting tomcat6 service\033[0m"
sudo service tomcat6 start