#!/usr/bin/env ruby

require "rubygems"
require "pony"

oldrev, newrev = ARGV

if oldrev =~ /^0+$/
  git_log = `git log --stat #{oldrev}..#{newrev}`
else
  git_log = `git log --stat`
end

Pony.mail(:to          => "admin@edify.cr",
          :from        => "deploy@edify.cr",
          :subject     => "Deploy CHANGEME APP on #{`hostname`.strip}",
          :body        => "Old revision: #{oldrev}\nNew revision: #{newrev}\n\n\nChangelog:\n\n#{git_log}",
          :via         => :sendmail,
          :via_options => {}